<?php

namespace App\Filament\Organization\Pages\Auth;

use App\Enums\UserRole;
use App\Models\Organization;
use App\Models\User;
use Filament\Auth\Pages\Register as BaseRegister;
use Filament\Forms\Components\TextInput;
use Filament\Schemas\Components\Wizard;
use Filament\Schemas\Schema;
use Filament\Support\Enums\Width;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Hash;

class Register extends BaseRegister
{
    protected Width|string|null $maxWidth = Width::TwoExtraLarge;

    public function form(Schema $schema): Schema
    {
        return $schema
            ->schema([
                Wizard::make([
                    Wizard\Step::make('Personal Information')
                        ->label('Shaxsiy ma\'lumotlar')
                        ->schema([
                            TextInput::make('first_name')
                                ->label('Ism')
                                ->required()
                                ->maxLength(255)
                                ->autofocus(),

                            TextInput::make('last_name')
                                ->label('Familiya')
                                ->required()
                                ->maxLength(255),

                            TextInput::make('phone_number')
                                ->label('Telefon raqam')
                                ->tel()
                                ->columnSpanFull()
                                ->prefix('+998')
                                ->placeholder('93 895 16 02')
                                ->mask('99 999 99 99')
                                ->required()
                                ->afterStateUpdated(function ($state, callable $set) {
                                    $set('phone_number', preg_replace('/\D/', '', $state));
                                })
                                ->unique('users', 'phone_number', ignoreRecord: true)
                                ->validationMessages([
                                    'unique' => 'Bu telefon raqam allaqachon ro\'yxatdan o\'tgan.',
                                ]),
                            $this->getPasswordFormComponent(),
                            $this->getPasswordConfirmationFormComponent(),
                        ])
                        ->columns(2),

                    Wizard\Step::make('Organization Information')
                        ->label('Tashkilot ma\'lumotlari')
                        ->schema([
                            TextInput::make('organization_name')
                                ->label('Tashkilot nomi')
                                ->required()
                                ->maxLength(255),

                            TextInput::make('organization_tin')
                                ->label('INN (STIR)')
                                ->required()
                                ->numeric()
                                ->length(9)
                                ->unique('organizations', 'tin', ignoreRecord: true)
                                ->validationMessages([
                                    'unique' => 'Bu INN allaqachon ro\'yxatdan o\'tgan.',
                                    'length' => 'INN 9 ta raqamdan iborat bo\'lishi kerak.',
                                ]),
                            TextInput::make('organization_address')
                                ->label('Manzil')
                                ->maxLength(500)
                                ->columnSpanFull(),
                        ])
                        ->columns(2),
                ])
                    ->submitAction(view('filament.organization.components.register-submit-button'))
                    ->columnSpanFull(),
            ]);
    }

    public function getFormActions(): array
    {
        return []; // TODO: Change the autogenerated stub
    }

    protected function beforeValidate()
    {
        $data = $this->data;
        // Telefon raqamni tozalaymiz
        $phone = preg_replace('/\D/', '', $data['phone_number']);
        if (!str_starts_with($phone, '998')) {
            $phone = '998' . $phone;
        }
        $data['phone_number'] = $phone;
        $this->data = $data;
    }

    protected function handleRegistration(array $data): Model
    {
        // Telefon raqamni tozalaymiz
        $phone = preg_replace('/\D/', '', $data['phone_number']);
        if (!str_starts_with($phone, '998')) {
            $phone = '998' . $phone;
        }
        // Avval user yaratamiz
        $user = User::query()->create([
            'first_name' => $data['first_name'],
            'last_name' => $data['last_name'],
            'phone_number' => $phone,
            'password' => Hash::make($data['password']),
            'role' => UserRole::ORGANIZATION,
        ]);

        // Keyin organization yaratamiz
        $organization = Organization::query()->create([
            'name' => $data['organization_name'],
            'tin' => $data['organization_tin'],
            'address' => $data['organization_address'] ?? null,
            'is_active' => true,
            'user_id' => $user->id,
        ]);

        return $user;
    }
}
